name: Compile and Release

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/maven.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    name: Maven Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn clean package -B -DskipTests

      - name: Upload JAR to Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ env.commit_id }}
          name: maven-build-${{ env.commit_id }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}